version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: backend-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: venkatesh
      POSTGRES_PASSWORD: venkatesh
      POSTGRES_DB: stefan-db
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: